---
apiVersion: v1
kind: Namespace
metadata:
  name: pki
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: otel
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
